### ISSUE TITLE
hardcoded namespace, should we switch the casc.yaml to a configmap and use helm to configure it?

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jenkins-x-serverless#268]
just noticed this https://github.com/jenkins-x/jenkins-x-serverless/blob/master/casc.yml#L19.  We could switch the yaml to be mounted and then we can override config options via helm values.yaml.

**Comment by jglick** [comment]
While you are at it, I suspect a bunch of sections there are superfluous, though am not sure how to test my hypothesis easily.

```yaml
plugins:
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
```

surely makes no sense for a prebaked image.

```yaml
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  disableRememberMe: false
```

is meaningless when there is no `securityRealm`.

```yaml
  primaryView:
    all:
      name: "all"
  views:
  - all:
      name: "all"
```

is meaningless when there is UI.

```yaml
  quietPeriod: 5
```

is either undesirable (ought to be set to zero), or unused.

```yaml
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
```

is the default, and since `checkout scm` uses a hard-coded “workspace” this would anyway only be used if someone ran the `git` step in their `Jenkinsfile` to pull in some _other_ repository.
